# Generated by Django 5.2.17 on 2026-08-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_student_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('speed', models.IntegerField(default=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
